config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  resources :routes
  resources :carriages

  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/train.rb
# frozen_string_literal: true

class Train < ApplicationRecord
  validates :number, presence: true

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  has_many :carriages

  def seats_count(carriage_type, *args)
    args.each { |seat_type| puts "Sum of #{seat_type} - #{carriages.where(type: carriage_type).sum(&seat_type.to_sym)}" }
  end

  def train_carriages_info
    train_carriages = {}
    Carriage.carriage_types.each do |type|
      carriages_by_type = carriages.select { |carriage| carriage.type == type }
      train_carriages[type] = { count: carriages_by_type.size,
                                top_seats: carriages_by_type.sum(&:top_seats),
                                side_top_seats: carriages_by_type.sum(&:side_top_seats),
                                side_bottom_seats: carriages_by_type.sum(&:side_bottom_seats),
                                seats: carriages_by_type.sum(&:seats) }
    end
    train_carriages
  end

  def ordered
    if sort
      carriages.order(number_in_train: :desc)
    else
      carriages.order(:number_in_train)
    end
  end
end

app/controllers/trains_controller.rb
# frozen_string_literal: true

class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
    @train_carriages = @train.train_carriages_info
  end

  def new
    @train = Train.new
  end

  def edit; end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train, notice: 'Train was successfully created.'
    else
      render :new
    end
  end

  def update
    if @train.update(train_params)
      redirect_to @train, notice: 'Train was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_path, notice: 'Train was successfully destroyed.'
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number, :current_station_id, :route_id, :sort)
  end
end

app/helpers/trains_helper.rb
# frozen_string_literal: true

module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_with(model: train, local: true) do |form| %>
  <%= render 'common/errors', resourse: @train %>

  <div class="field">
    <%= form.check_box :sort %>
    <%= form.label("From tail") %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :current_station, "Current station" %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title  %>
  </div>

  <div class="field">
    <%= form.label :route, "Current route" %>
    <%= form.collection_select :route_id, Route.all, :id, :name  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Show', train %></td>
  <td><%= link_to 'Edit', edit_train_path(train) %></td>
  <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<p>
  <strong>On station:</strong>
  <% if @train.current_station.present? %>
    <%= @train.current_station.title %>
  <% else %>
    No stations
  <% end %>
</p>

<p>
  <strong>Carriages of train</strong>
  <% @train.ordered.each do |carriage| %>
    <p><%= link_to "Carriage№#{carriage.number_in_train}", carriage_path(carriage) %></p>
  <% end %>
</p>

<table border="1">
  <% @train_carriages.each do |type, count_values |%>
    <td>
      <th><%= "#{type}" %> counts: </th>
    </td>
      <% count_values.each do |seat, count| %>
        <tr>
          <th><%= "#{seat}:" %></th>
          <th><%= "#{count}" %></th>
        </tr>
      <% end %>
  <% end %>
</table>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>