config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  resources :routes
  resources :carriages

  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/carriage.rb
# frozen_string_literal: true

class Carriage < ApplicationRecord
  belongs_to :train

  validates :number, presence: true

  after_create :add_number_in_train

  CARRIAGE_TYPES = %w[EconomyCarriage CoupeCarriage SVCarriage SeatedCarriage].freeze

  def self.carriage_types
    CARRIAGE_TYPES
  end

  def add_number_in_train
    carriages_in_train = Carriage.where(train_id: train_id)
    number_in_train_presented = carriages_in_train.select { |carriage| carriage.number_in_train.present? }
    if number_in_train_presented.present?
      number_in_train_to_update = number_in_train_presented.map(&:number_in_train).max + 1
      update(number_in_train: number_in_train_to_update)
    else
      update(number_in_train: 1)
    end
  end
end

app/controllers/carriages_controller.rb
# frozen_string_literal: true

class CarriagesController < ApplicationController
  before_action :set_carriage, only: [:show, :edit, :update, :destroy]
  def index
    @carriages = Carriage.all
  end

  def show; end

  def new
    @carriage = Carriage.new
  end

  def create
    @carriage = Carriage.new(carriage_params)
    if @carriage.save
      redirect_to @carriage.becomes(Carriage)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @carriage.update(carriage_params)
      redirect_to @carriage.becomes(Carriage)
    else
      render :edit
    end
  end

  def destroy
    @carriage.destroy
    redirect_to carriages_path, notice: 'Carriage was successfully destroyed.'
  end

  private

  def set_carriage
    @carriage = Carriage.find(params[:id])
  end

  def carriage_params
    params.require(:carriage).permit(:number, :top_seats, :bottom_seats, :side_top_seats, :side_bottom_seats, :seats, :train_id, :type)
  end
end

app/views/carriages/_carriage.html.erb
<tr>
  <td><%= carriage.number %></td>
  <td><%= carriage.type %></td>
  <td><%= "№#{carriage.train.number}" %></td>
  <td><%= link_to 'Show', link_to(carriage.train.number, controller: "carriages", action: "show", id: carriage) %></td>
  <td><%= link_to 'Edit', edit_carriage_path(carriage) %></td>
  <td><%= link_to 'Destroy', { :controller => 'carriages', :action => 'destroy', :id => carriage },
                              { :confirm => 'Are you sure?', :method => :delete, :remote => true } %></td>
</tr>

app/views/carriages/_carriage_in_train.html.erb
<tr>
  <td><%= link_to "Carriage№#{carriage.number_in_train}", carriage_path(carriage) %></td>
</tr>

app/views/carriages/_form.html.erb
<%= form_with(model: carriage.becomes(Carriage), local: true) do |form| %>
  <%= render 'common/errors', resourse: carriage %>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.select :type, options_for_select([['EconomyCarriage'],['CoupeCarriage'],['SVCarriage'],['SeatedCarriage']]) %>
  </div>

  <div class="field">
    <%= form.label :top_seats %>
    <%= form.text_field :top_seats %>
    Economy, Coupe
  </div>

  <div class="field">
    <%= form.label :bottom_seats %>
    <%= form.text_field :bottom_seats %>
    Economy, Coupe, SV
  </div>

  <div class="field">
    <%= form.label :side_top_seats %>
    <%= form.text_field :side_top_seats %>
    Economy
  </div>

  <div class="field">
    <%= form.label :side_bottom_seats %>
    <%= form.text_field :side_bottom_seats %>
    Economy
  </div>

  <div class="field">
    <%= form.label :seats %>
    <%= form.text_field :seats %>
    Seated
  </div>


  <div class="field">
    <%= form.label :train, 'Train' %>
    <%= form.collection_select :train_id, Train.all, :id, :number %>
  </div>


  <div class="actions">
    <%= form.submit "#{ @carriage.new_record? ? 'Create' : 'Edit' }" %>
  </div>
<% end %>

app/views/carriages/edit.html.erb
<h1>Edit Carriage</h1>

<%= render 'form', carriage: @carriage %>

<%= link_to 'Back', carriages_path %>

app/views/carriages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of carriages</h1>

<table>
  <thead>
    <tr>
      <th>Number |</th>
      <%# <th colspan="3"></th> %>
      <th>Carriage type</th>
      <th>Train number</th>

      <%# <th colspan="3"></th> %>
    </tr>

  </thead>

  <tbody>
    <%= render partial: 'carriages/carriage', collection: @carriages, as: :carriage %>
  </tbody>
</table>

<br>

<%= link_to 'New Carriage', new_carriage_path %>

app/views/carriages/new.html.erb
<h1>New Carriage</h1>

<%= render 'form', carriage: @carriage %>

<%= link_to 'Back', carriages_path %>

app/views/carriages/show.html.erb
<p id="notice"><%= notice %></p>

<table><strong>Carriage info:</strong>
  <tr><td>Number - <%= @carriage.number %></td></tr>
  <tr><td>Type - <%= @carriage.type %></td></tr>
  <tr><td>Top seats - <%= @carriage.top_seats %></td></tr>
  <tr><td>Bottom seats - <%= @carriage.bottom_seats %></td></tr>
  <tr><td>Side Top seats - <%= @carriage.side_top_seats %></td></tr>
  <tr><td>Side Bottom seats - <%= @carriage.side_bottom_seats %></td></tr>
  <tr><td>Seats - <%= @carriage.seats %></td></tr>
  <tr><td>Train №- <%= @carriage.train_id %></td></tr>
</table>

<%= link_to 'Edit', edit_carriage_path(@carriage) %> |
<%= link_to 'Back', carriages_path %>