config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  resources :routes
  resources :carriages

  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/route.rb
# frozen_string_literal: true

class Route < ApplicationRecord
  has_many :railway_stations_routes, dependent: :destroy
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name

  def update_position(station, position)
    exist_station_with_position = RailwayStationsRoute.find_by(route_id: id, position: position) # существующая станция с позицоей position
    (errors.add(:base, 'Position should be existed before') && return) if exist_station_with_position.nil?
    station_in_route = RailwayStationsRoute.find_by(route_id: id, railway_station_id: station.id) # станция которую нужно поменять
    exist_station_with_position.update(position: station_in_route.position) # меняем станцию которая была с этой позицией на позицию чтанции которую мы меняем
    station_in_route.update(position: position) # меняем позицию заданной станции на зажанную позицию
  end

  private

  def set_name
    self.name = "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    errors.add(:base, 'Route should contain at least 2 stations') if railway_stations.size < 2
  end
end

app/controllers/routes_controller.rb
# frozen_string_literal: true

class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  def index
    @routes = Route.all
  end

  def show; end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit; end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path, notice: 'Route was successfully destroyed.'
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:name, railway_station_ids: [])
  end
end

app/views/routes/_form.html.erb
<%= form_with(model: @route, local: true) do |form| %>
  <%= render 'common/errors', resourse: @route %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :railway_station_ids, "Stations" %>
    <%= form.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>

  <div class="actions">
    <%= form.submit "#{ @route.new_record? ? 'Create' : 'Edit' }" %>
  </div>
<% end %>

app/views/routes/_route.html.erb
<tr>
  <td><%= route.name %></td>
  <td><%= link_to 'Show', route %></td>
  <td><%= link_to 'Edit', edit_route_path(route) %></td>
  <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/routes/edit.html.erb
<h1>Edit Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List of routes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @routes %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>
<p>
  <strong>Trains on the route: </strong>
  <% if @route.trains.present? %>
    <ul>
      <% @route.trains.each do |train| %>
        <li><%= train.number %></li>
      <% end %>
    </ul>
  <% else %>
    No trains
  <% end %>
</p>

<p>
  <strong>Stations:</strong>
  <% if @route.railway_stations.empty? %>
    No stations
  <% else %>
    <table>
      <thead>
      <tr>
        <td width="100px">Title</td>
        <td>Position</td>
      </tr>
      </thead>
      <tbody>
      <% @route.railway_stations.order(:position).each do |station| %>
          <tr>
            <td><%= station.title %></td>
            <td><%= station.position(@route) %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% end %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>